name: build-dev
on:
  push:
    branches: [ dev, dev-ci-experiment ]
  pull_request:
    branches: [ dev ]

jobs:
    linux-gcc-13:
        name: Linux GCC 13
        runs-on: ubuntu-22.04
        container:
          image: gcc:13.2.0
          env:
            CC: gcc-13
            CXX: g++-13
        steps:
            - uses: actions/checkout@v3
            #- run: |
            #      sudo apt-get update
            #      sudo apt-get install -y ninja-build build-essential valgrind libicu-dev
            - run: /bin/bash .ci/build-project.sh build-simple
            - run: ./build-simple/test/ael-tests
            - run: ./build-simple/benchmark/test/benchmark-lib-tests
            - run: /bin/bash .ci/build-project-valgrind.sh build-valgrind
            - run: valgrind ./build-valgrind/test/ael-tests
            - run: valgrind ./build-valgrind/benchmark/test/benchmark-lib-tests

    linux-clang-16-libstdcpp:
        name: Linux Clang 16 (libstdc++)
        runs-on: ubuntu-22.04
        env:
            CC: clang-16
            CXX: clang++-16
            CXXFLAGS: -stdlib=libstdc++
        steps:
            - uses: actions/checkout@v3
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y ninja-build libc6-dbg
                  sudo snap install valgrind --classic
                  wget https://apt.llvm.org/llvm.sh
                  chmod +x llvm.sh
                  sudo ./llvm.sh 16
                  sudo apt-get install -y ninja-build build-essential libstdc++-13-dev valgrind libicu-dev
            - run: /bin/bash .ci/build-project.sh build-simple
            - run: ./build-simple/test/ael-tests
            - run: ./build-simple/benchmark/test/benchmark-lib-tests
            - run: /bin/bash .ci/build-project-valgrind.sh build-valgrind
            - run: valgrind ./build-valgrind/test/ael-tests
            - run: valgrind ./build-valgrind/benchmark/test/benchmark-lib-tests

    linux-clang-16-libcpp:
        name: Linux Clang 16 (libc++)
        runs-on: ubuntu-22.04
        env:
            CC: clang-16
            CXX: clang++-16
            CXXFLAGS: -stdlib=libc++
        steps:
            - uses: actions/checkout@v3
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y ninja-build libc6-dbg
                  sudo snap install valgrind --classic
                  wget https://apt.llvm.org/llvm.sh
                  chmod +x llvm.sh
                  sudo ./llvm.sh 16
                  sudo apt-get install -y libc++-16-dev libc++abi-16-dev ninja-build build-essential valgrind libicu-dev
            - run: /bin/bash .ci/build-project.sh build-simple
            - run: ./build-simple/test/ael-tests
            - run: ./build-simple/benchmark/test/benchmark-lib-tests
            - run: /bin/bash .ci/build-project-valgrind.sh build-valgrind
            - run: valgrind ./build-valgrind/test/ael-tests
            - run: valgrind ./build-valgrind/benchmark/test/benchmark-lib-tests
