name: build-dev
on:
  push:
    branches: [ dev, dev-ci-experiment ]
  pull_request:
    branches: [ dev ]

jobs:
    linux-gcc:
        name: Linux GCC
        runs-on: ubuntu-22.04
        container:
          image: gogagum/cool_linux_build_container:latest
          env:
            CC: gcc
            CXX: g++
        steps:
            - uses: actions/checkout@v3
            - run: /bin/bash .ci/build-project.sh build-simple
            - run: ./build-simple/test/ael-tests
            - run: ./build-simple/benchmark/test/benchmark-lib-tests
            - run: /bin/bash .ci/build-project-valgrind.sh build-valgrind
            - run: valgrind ./build-valgrind/test/ael-tests
            - run: valgrind ./build-valgrind/benchmark/test/benchmark-lib-tests


    linux-clang-libstdcpp:
        name: Linux Clang (libstdc++)
        runs-on: ubuntu-22.04
        container:
          image: ghcr.io/foonathan/clang:16
          env:
            CC: clang
            CXX: clang++
            CXXFLAGS: -stdlib=libstdc++
        steps:
            - uses: actions/checkout@v3
            - run: /bin/bash .ci/build-project.sh build-simple
            - run: ./build-simple/test/ael-tests
            - run: ./build-simple/benchmark/test/benchmark-lib-tests
            - run: /bin/bash .ci/build-project-valgrind.sh build-valgrind
            - run: valgrind ./build-valgrind/test/ael-tests
            - run: valgrind ./build-valgrind/benchmark/test/benchmark-lib-tests

    linux-clang-libcpp:
        name: Linux Clang (libc++)
        runs-on: ubuntu-22.04
        container:
          image: ghcr.io/foonathan/clang:16
          env:
            CC: clang
            CXX: clang++
            CXXFLAGS: -stdlib=libc++
        steps:
            - uses: actions/checkout@v3
            - run: /bin/bash .ci/build-project.sh build-simple
            - run: ./build-simple/test/ael-tests
            - run: ./build-simple/benchmark/test/benchmark-lib-tests
            - run: /bin/bash .ci/build-project-valgrind.sh build-valgrind
            - run: valgrind ./build-valgrind/test/ael-tests
            - run: valgrind ./build-valgrind/benchmark/test/benchmark-lib-tests

