name: build-dev
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
    linux-gcc:
        name: Linux GCC
        runs-on: ubuntu-22.04
        env:
            CC: gcc-12
            CXX: g++-12
        steps:
            - uses: actions/checkout@v3
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y ninja-build g++-12 libstdc++-12-dev build-essential python-dev autotools-dev libicu-dev libbz2-dev valgrind libboost-all-dev
            - run: |
                  wget -O boost_1_81_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.81.0/boost_1_81_0.tar.gz/download
                  tar xzvf boost_1_81_0.tar.gz
                  cd boost_1_81_0/
                  ./bootstrap.sh --prefix=/usr/
                  ./b2
                  sudo ./b2 install
            - run: /bin/bash .ci/build-project.sh build-simple
            - run: ./build-simple/test/ael-tests
            - run: /bin/bash .ci/build-project-valgrind.sh build-valgrind
            - run: valgrind ./build-valgrind/test/ael-tests
